### PR TITLE
fix: coverage yields empty reports

### LINKED ISSUE #245: karma-preset: Empty coverage report
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Enable `coverage: true` in `poi-preset-karma` config and you should get a lcov report.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the example in the preset and see that lcov.info turns out 0 size:

```
0 drwxr-xr-x  8 mblarsen  staff  272 Oct  2 13:18 lcov-report
0 -rw-r--r--  1 mblarsen  staff    0 Oct  2 13:18 lcov.info
```

**What is the expected behavior?**

A valid non-empty lcov report.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Poi: 9.3.8
Node: 8.6.0
OS: macOS Sierra

### PR DESCRIPTION
**Pull request by mblarsen**
Fix for #245 

The coverage preprocessor was never added when enabling `coverage`. It was only added as reporter.

--- 

*UPDATE*: After submitting the first PR the code has gone in a different direction after reading hundreds of githubs issues, PRs, boilerplates, etc. 

`coverage` should _not_ be a preprocessor and also you don't have to add your src files to `files` it is enough to include the test files.

### CODE REVIEW

**Comment by mblarsen** [comment]
Although this fixes the issue there are some remaining issues:

1. Everything in `files` will be covered.
2. You'll need to add your source files to `files` as well. Not just the tests.
3. The coverage is of the webpack'ed files. Not the source files. I'm wondering if this https://github.com/webpack-contrib/istanbul-instrumenter-loader should be used.

For 1-2 I suggest explicitly telling what to cover:

```
   coverage: true,
   coverFiles: [ 'src/*.js' ],
```

And then use that to concat to `files` and use directly in `preprocessors` instead of reducing over `files`.

These should probably be split out into new issues.

**Comment by mblarsen** [comment]
@egoist I'll examine this further. It shouldn't be necessary to specify the source files, so something else must be wrong. 

Please ignore this PR for now :)

**Comment by mblarsen** [comment]
Maaaan, this took some time to get right. There are so many test/coverage/transpiler modules out there that are influx. This is not the time for coverage of es6 with tests written in es6 hehe. 

But it works now:

screen shot 2017-10-07 at 8 44 23 pm

A key part of getting it to work was to use an old version of jasmine-instrumenter-loader as the never versions doesn't work with html and lcov reporters (only lcovonly reporter).

**Comment by egoist** [comment]
does this work on .vue files?

**Comment by mblarsen** [comment]
Not sure, will test.

**Comment by mblarsen** [comment]
It does work, however it will includes other files as well -- used to transpile vue.

**Comment by mblarsen** [comment]
screen shot 2017-10-07 at 9 34 32 pm


Not ideal, will try to get rid of those.

**Comment by mblarsen** [comment]
I think I might need to do something like this https://github.com/vuejs/vue-loader/issues/7#issuecomment-111878649 to get it working correctly with vue.

**Comment by mblarsen** [comment]
Also this may be relevant: https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/73

**Comment by mblarsen** [comment]
Btw, for context `coverage: true` doesn't work for anything prior to this PR. But I think we should get vue (and possible and others) to work also before merging anything.

**Comment by mblarsen** [comment]
@egoist I got code coverage working on both regular js and on vue. Also I sorted out the excess files included in the reports to that the coverage values are now accurate.

There is one part of the solution I'm not particular happy with and I was wondering if there are other ways to modify and existing loader than the way I am doing. (the mapping of rules part)

js:

screen shot 2017-10-09 at 1 42 59 pm

vue:

screen shot 2017-10-09 at 1 43 10 pm

File: packages/poi-preset-karma/index.js [hunk 1]
```diff
@@ -76,6 +71,32 @@ module.exports = (options = {}) => {
...
+            enforce: 'post',
+            loader: 'istanbul-instrumenter-loader',
+            query: {
+              esModules: true
+            }
+          }
+        ].concat(webpackConfig.module.rules)
+        /* for vue (assumes vue-loader) */
+        webpackConfig.module.rules = webpackConfig.module.rules
+          .map(r => {
```
Comment (mblarsen) [inline packages/poi-preset-karma/index.js]: @egoist is there a better way to modify the webpack config than mapping over its rules like this?

File: packages/poi-preset-karma/index.js [hunk 2]
```diff
@@ -76,6 +71,36 @@ module.exports = (options = {}) => {
...
+            exclude: /(node_modules|\.test\.jsx?)/,
+            enforce: 'post',
+            loader: 'istanbul-instrumenter-loader',
+            query: {
+              esModules: true
+            }
+          }
+        ].concat(webpackConfig.module.rules)
+        /* for vue (assumes vue-loader) */
+        webpackConfig.module.rules = webpackConfig.module.rules
```
Comment (egoist) [inline packages/poi-preset-karma/index.js]: actually you can update webpack config in `poi.extendWebpack('test', config => {})` using webpack-chain

Comment (egoist) [reply packages/poi-preset-karma/index.js]: I will update this :)

File: packages/poi-preset-karma/index.js [hunk 3]
```diff
@@ -76,6 +71,36 @@ module.exports = (options = {}) => {
...
+          .map(r => {
+            const vueLoaderPos = r.use && r.use.findIndex(u => u.loader === 'vue-loader')
+            if (typeof vueLoaderPos === 'undefined' || vueLoaderPos === -1) {
+              return r
+            }
+            const options = r.use[vueLoaderPos].options
+            const instrumenterLoader = 'istanbul-instrumenter-loader?esModules=true'
+            options.preLoaders = (options.preLoaders || {})
+            options.preLoaders.js = typeof options.preLoaders.js === 'string' ?
```
Comment (egoist) [inline packages/poi-preset-karma/index.js]: why it's preLoader for .vue file but postLoader for .js file?

Comment (mblarsen) [reply packages/poi-preset-karma/index.js]: Actually it should be pre for both. If you use post it will run the coverage after the `babel-plugin-add-module-exports` has run which adds something like this to the top:

screen shot 2017-10-10 at 1 51 11 pm

Do you want me to change both to pre (as they should be) or can you correct it when you add the webpack-chain stuff @egoist

File: packages/poi-preset-karma/index.js (hunk 2 above)
Comment (mblarsen) [reply packages/poi-preset-karma/index.js]: Thanks. I'm new to `webpack-chain` will check it out. It looks promising.

File: packages/poi-preset-karma/index.js (hunk 3 above)
Comment (egoist) [reply packages/poi-preset-karma/index.js]: thanks I will webpack-chain-ify it later today
